# Generated by Django 2.2.7 on 2019-11-21 11:30

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191116_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.TimeField(default=myapp.models.default_start_time),
        ),
        migrations.AddField(
            model_name='flight',
            name='dept',
            field=models.DateTimeField(default=myapp.models.default_start_time),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flight',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trains',
            name='arrival',
            field=models.TimeField(default=myapp.models.default_start_time),
        ),
        migrations.AddField(
            model_name='trains',
            name='dept',
            field=models.TimeField(default=myapp.models.default_start_time),
        ),
        migrations.AddField(
            model_name='trains',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trains',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trains',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trains',
            name='train_class',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
