# Generated by Django 2.2.7 on 2019-11-25 11:17

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191121_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(default='', max_length=15)),
                ('bus_number', models.IntegerField(unique=True)),
                ('origin', models.CharField(default='', max_length=4)),
                ('dest', models.CharField(default='', max_length=4)),
                ('duration', models.FloatField(default=0.0)),
                ('dept', models.DateTimeField(default=myapp.models.default_start_time)),
                ('arrival', models.DateTimeField(default=myapp.models.default_start_time)),
                ('bus_class', models.CharField(default='', max_length=20)),
                ('seats', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='', max_length=20)),
                ('hotel_description', models.CharField(default='', max_length=50)),
                ('hotel_address', models.CharField(default='', max_length=50)),
                ('hotel_city', models.CharField(default='', max_length=4)),
                ('hotel_zip', models.IntegerField(default=0)),
                ('hotel_beds', models.IntegerField(default=0)),
                ('hotel_baths', models.IntegerField(default=0)),
                ('hotel_rooms', models.IntegerField(default=0)),
                ('hotel_kitchen', models.BooleanField(default=False)),
                ('hotel_ac', models.BooleanField(default=False)),
                ('hotel_class', models.CharField(default='', max_length=15)),
                ('available_rooms', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
