# Generated by Django 2.2.7 on 2019-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flight_flight_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(unique=True),
        ),
    ]
