# Generated by Django 2.2.7 on 2019-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191116_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='dest',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='trains',
            name='origin',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='trains',
            name='train_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
