# Generated by Django 2.2.7 on 2019-11-21 11:37

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191121_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=myapp.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='trains',
            name='arrival',
            field=models.DateTimeField(default=myapp.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='trains',
            name='dept',
            field=models.DateTimeField(default=myapp.models.default_start_time),
        ),
    ]
