# Generated by Django 2.2.7 on 2019-11-30 10:48

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191130_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=myapp.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dept',
            field=models.DateTimeField(default=myapp.models.default_start_time),
        ),
    ]
