# Generated by Django 2.2.7 on 2019-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191130_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
