# Generated by Django 2.2.7 on 2019-11-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191130_1630'),
        ('myapp', '0010_auto_20191130_2343'),
    ]

    operations = [
    ]
