# Generated by Django 2.2.7 on 2019-11-30 18:22

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_merge_20191130_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=myapp.models.default_start_time),
        ),
        migrations.AddField(
            model_name='flight',
            name='deptTime',
            field=models.TimeField(default=myapp.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.DateField(default=myapp.models.default_start_date),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dept',
            field=models.DateField(default=myapp.models.default_start_date),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
