# Generated by Django 2.2.7 on 2019-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20191130_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
