# Generated by Django 2.2.7 on 2019-12-01 08:45

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_flight_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='arrivalTime',
            field=models.TimeField(default=myapp.models.default_start_time),
        ),
        migrations.AddField(
            model_name='trains',
            name='deptTime',
            field=models.TimeField(default=myapp.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='trains',
            name='arrival',
            field=models.DateField(default=myapp.models.default_start_date),
        ),
        migrations.AlterField(
            model_name='trains',
            name='dept',
            field=models.DateField(default=myapp.models.default_start_date),
        ),
    ]
