# Generated by Django 2.2.7 on 2019-12-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20191201_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='train_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
