# Generated by Django 2.2.7 on 2019-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20191201_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='guests_per_room',
            field=models.IntegerField(default=0),
        ),
    ]
