# Generated by Django 2.2.7 on 2019-12-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_hotel_guests_per_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline_cover',
            field=models.ImageField(blank=True, upload_to='airline_images'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_cover',
            field=models.ImageField(blank=True, upload_to='hotel_images'),
        ),
    ]
