# Generated by Django 2.2.7 on 2019-12-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20191201_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_cover',
            field=models.ImageField(blank=True, upload_to='mdeia/airline_images'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_cover',
            field=models.ImageField(blank=True, upload_to='media/hotel_images'),
        ),
    ]
