# Generated by Django 2.2.7 on 2019-12-03 10:49

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_hotel_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='travellers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='timestamp',
            field=models.DateTimeField(default=myapp.models.default_start_time),
        ),
    ]
