# Generated by Django 2.2.7 on 2019-12-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20191203_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='travellers',
            field=models.IntegerField(default=1),
        ),
    ]
