# Generated by Django 2.2.7 on 2019-12-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20191203_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
