# Generated by Django 2.2.7 on 2019-12-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_hotel_hotel_number_of_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='totalPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
