# Generated by Django 2.2.7 on 2019-12-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_hotel_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='totalPrice',
        ),
    ]
